[tool.ruff]
target-version = "py311"
line-length = 100
src = [
    "packages/plotstyle/src",
    "packages/qspectro2d/src",
    "scripts"
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "B",
    "I",
    "UP",
    "S",
    "C4"
]
ignore = [
    "E203",
    "E501"
]

[tool.black]
line-length = 100
preview = true

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = [
    "packages/plotstyle/src",
    "packages/qspectro2d/src"
]

[tool.coverage.run]
branch = true
source = [
    "packages/plotstyle/src",
    "packages/qspectro2d/src"
]
