[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qspectro2d"
version = "0.1.0"
description = "Quantum 1D/2D electronic spectroscopy simulations for the thesis"
requires-python = ">=3.11"
authors = [
  {name = "Leopold Bodamer"}
]

[project.urls]
Repository = "https://github.com/LBPhysics/2025_master_thesis_python_leopold_bodamer"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["qspectro2d"]
namespaces = false


